### PR TITLE
fix: missing handler callback for I2S DMA duplex circular mode

### PR DESCRIPTION
**Pull request by lukasnee**
### Contributor License Agreement (CLA)
* The Pull Request feature will be considered by STMicroelectronics after the signature of a **Contributor License Agreement (CLA)** by the submitter.
* If you did not sign such agreement, please follow the steps mentioned in the [CONTRIBUTING.md](https://github.com/STMicroelectronics/STM32CubeF3/blob/master/CONTRIBUTING.md) file.

### CODE REVIEW

**Comment by lukasnee** [comment]
This pull request relates to this issue: https://github.com/STMicroelectronics/STM32CubeF3/issues/13

**Comment by ASELSTM** [comment]
Hi @lukasnee,

Thank you your contribution. Actually, the point you raised has already been dealt and fixed internally. The fix will be made available in the frame of a future release.

We cannot share a date for the moment. So stay tuned and thank you once more for your contribution and for your patience.

With regards

**Comment by ASELSTM** [comment]
ST Internal Reference: 51805

**Comment by ASELSTM** [comment]
Hi @lukasnee,

The issue you reported has been fixed in the frame of version v1.11.3 of the STM32CubeF3 published on GitHub.

Please allow me then to close this thread and thank you again for having reported.

With regards,

**Pull request closed without merging**
